name: Bug Report
description: File a new bug report
title: 'bug: <title>'
labels: [Needs Triage]
body:
  - type: markdown
    attributes:
      value: >
          If this issue is with Dynamo for Revit, please post your issue on the [DynamoRevit](https://github.com/DynamoDS/DynamoRevit/issues/new).
          
          If this is feature request, please post your issue on the [DynamoWishlist](https://github.com/DynamoDS/DynamoWishlist/issues/new).
          
          If this issue is not a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
  - type: textarea
    attributes:
      label: 'Dynamo Version'
      description: >-
        Which version of Dynamo are you using?
        
        Go to **Dynamo > About** if you are not sure.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Host Version'
      description: 'Which host are you using? (e.g Revit 2024.1).'
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Operating System'
      description: 'e.g Windows 10, Windows 11'
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'What did you do?'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'What did you expect to see?'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'What did you see instead?'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Stacktrace/logs'
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Details'
      description: |
        Links? References?
        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in it._
    validations:
      required: false
