name: Python shell

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: python
        run: |
          import json
          import os

          print("${{ github.repository }}")
          job_status = ${{ toJson(job) }}['status'].upper()
          print(job_status)
          print("${{ job.status }}")
          run_url = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          print(run_url)
