# Build Dynamo using latest VS and DotNET
name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          mkdir build
          echo "hello world" >> "${{ github.workspace }}/build/test-$(date +"%Y-%m-%d-%H-%M").txt"
      - name: List files
        run: ls -LR
      - name: Save Build Cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ github.event.number }}
      - name: Save Pull Request Number
        run: echo ${{ github.event.number }} >> ${{ github.workspace }}/pr_number.txt
      - name: Upload Pull Request Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: ${{ github.workspace }}/pr_number.txt
          if-no-files-found: warn
          retention-days: 1
