# Build Dynamo using latest VS and DotNET
name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          mkdir build
          echo "hello world" >> "build/test-$(date +"%Y-%m-%d-%H-%M").txt"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/build
          if-no-files-found: warn
          retention-days: 3
