name: Check file size
on:
  - push
  - pull_request

jobs:
  check_file_size:
    name: Check file size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v40
        with:
          write_output_files: true
      - name: List changed files
        run: |
          for file in $(cat .github/outputs/all_changed_files.txt); do
            echo "${file}"
          done
      - name: Summary
        run: |
          echo "# Changed Files" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Files changed - ${{ steps.get_changed_files.outputs.all_changed_files.count }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for file in $(cat .github/outputs/all_changed_files.txt); do
            echo "- $(du -h ${file})" >> $GITHUB_STEP_SUMMARY
          done
      - name: Check file size
        run: |
          for file in $(cat .github/outputs/all_changed_files.txt); do
            [[ -n $(find "${file}" -type f -size +50M) ]] && { echo "❌ $file exceeds file size limit"; exit 1; } || echo "✅ $file"
          done
