name: Label Issues

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    name: Label Issues
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          configuration-path: .github/issue_labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          include-body: 1
      - name: Add comment
        env:
          GH_TOKEN: ${{ github.token }}
          COMMENT: Thank you for submitting the issue to us. We will look into it as soon as possible.
        run: gh issue comment ${{ github.event.issue.number }} --body "${{ env.COMMENT }}" --repo ${{ github.repository }}
