name: Label Issues

on:
  issues:
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  COMMENT: Thank you for submitting the issue to us. We will look into it as soon as possible.

jobs:
  label_issues:
    name: Label Issues
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/issue_labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          include-body: 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add comment
        run: gh issue comment ${{ env.ISSUE_NUMBER }} --body "${{ env.COMMENT }}"
