name: Move Issues

on:
  issues:
    types:
      - labeled

jobs:
  move_issue_labeled_as_tracked:
    name: Move issue labeled as tracked
    runs-on: ubuntu-latest
    if: github.event.label.name == 'tracked'
    steps:
      - name: Move tracked issue to Todo
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.TESTS_TOKEN }}
          user: ${{ github.repository_owner }}
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo
