name: pwsh

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: error
        shell: pwsh
        run: |
          Get-ChildItem -Path ${{ github.workspace }}\.github -Recurse
          $files = Get-ChildItem -Path ${{ github.workspace }}\.github -Recurse
          foreach ($file in $files) {
            Write-Output "::error file=$($file.FullName)::Missing version information"
          }
          $files | ForEach-Object {
            Write-Output "::error file=$($_.FullName)::Missing version information"
          }
