name: pwsh

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: error
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path ${{ github.workspace }}\.github -Recurse
          Write-Output "::error title=Missing version information::$(foreach ($file in $files) { $file.FullName })"
