name: Python shell

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: python
        run: |
          import json
          import os

          print("${{ github.repository }}")
          job_status = ${{ toJson(job) }}['status'].upper()
          print(job_status)
