name: Python shell

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: python
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          import json
          import os

          github_context = json.loads(os.environ['GITHUB_CONTEXT'])
          print(github_context)

          job_context = json.loads(os.environ['JOB_CONTEXT'])
          print(job_context)

          print("${{ github.repository }}")
          print("${{ toJson(job) }}")
