name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Test 1
        if: ${{ github.event_name == 'push' }} && {{ github.ref == 'refs/heads/develop' }}
        run: echo "Test 1"
      - name: Test 2
        if: ${{ github.event_name == 'push' &&  github.ref == 'refs/heads/develop' }}
        run: echo "Test 2"
