name: Test

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Download Artifact
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
          path: ${{ github.workspace }}/build
      - name: list files
        run: ls -LR
      - name: Summary
        run: |
          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "Actor: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
      - name: Summary - push
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo "Head Commit: [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})" >> $GITHUB_STEP_SUMMARY
      - name: Summary - workflow run
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo "Workflow: [${{ github.event.workflow_run.name }}](${{ github.event.workflow_run.html_url }})" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request: [${{ github.event.workflow_run.pull_requests[0].number }}](${{ github.event.workflow_run.pull_requests[0].url }})" >> $GITHUB_STEP_SUMMARY
