name: Test

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Restore build cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ env.PR_NUMBER }}
      - name: List files
        run: ls -LR
