name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: DynamoDS/DynamoTestCompleteTests
          token: ${{ secrets.TESTS_TOKEN }}
          ref: master
      - name: list files
        run: dir /s
