name: Test

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Download Artifact
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
          path: ${{ github.workspace }}/build
      - name: list files
        run: ls -al
