name: Test
run-name: Test - ${{ github.event.workflow_run.head_commit.message }}

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build
    types:
      - completed

env:
  EVENT_NAME: ${{ github.event_name }}
  ACTOR: ${{ github.actor }}
  WORKFLOW_ID: ${{ github.event.workflow_run.workflow_id }}
  RUN_NAME: ${{ github.event.workflow_run.name }}
  RUN_URL: ${{ github.event.workflow_run.html_url }}
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
  PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
  COMMIT_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
  COMMIT_URL: ${{ github.event.workflow_run.head_commit.url }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: env
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Download Artifact
        if: ${{ env.EVENT_NAME == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          workflow: ${{ env.WORKFLOW_ID }}
          path: ${{ github.workspace }}/build
      - name: Run script
        run: python .github/test.py
      - name: Summary
        run: |
          echo "# Summary" >> $GITHUB_STEP_SUMMARY
          echo "Actor: @${{ env.ACTOR }}" >> $GITHUB_STEP_SUMMARY
      - name: Summary - push
        if: ${{ env.EVENT_NAME == 'push' }}
        run: |
          echo "Head Commit: [${{ env.COMMIT_MESSAGE }}](${{ env.COMMIT_URL }})" >> $GITHUB_STEP_SUMMARY
      - name: Summary - workflow run
        if: ${{ env.EVENT_NAME == 'workflow_run' }}
        run: |
          echo "Workflow Run: [${{ env.RUN_NAME }}](${{ env.RUN_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request: [${{ env.PR_NUMBER }}](${{ env.PR_URL}})" >> $GITHUB_STEP_SUMMARY
