name: tmp

on:
  push:

jobs:
  tmp:
    name: tmp
    runs-on: windows-latest
    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |
            "COMMENT<<$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
            "## COMMENT" | Out-File -FilePath $env:GITHUB_ENV -Append
            "Title: This is a title" | Out-File -FilePath $env:GITHUB_ENV -Append
            "Body: This is a body" | Out-File -FilePath $env:GITHUB_ENV -Append
            "$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Print one
        run:
            Write-Host "${{ env.COMMENT }}"
      - name: Set the value in bash
        id: step_two
        shell: bash
        run: |
          {
            echo 'COMMENT<<EOF'
            echo "## Comment"
            echo "Title: This is a title"
            echo "Body: This is a body"
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Print two
        run:
            Write-Host "${{ env.COMMENT }}"
      - name: Create Pull Request Comment
        id: create_comment
        run: |
          "COMMENT1<<$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
          "## Comment"  | Out-File -FilePath $env:GITHUB_ENV -Append
          "Title: This is a title" | Out-File -FilePath $env:GITHUB_ENV -Append
          "Body: This is a body" | Out-File -FilePath $env:GITHUB_ENV -Append
          "$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Print Comment
        run:
            Write-Host "${{ env.COMMENT1 }}"
