name: tmp

on:
  push:

jobs:
  tmp:
    name: tmp
    runs-on: windows-latest
    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |
            $EOF = -join (1..15 | ForEach {[char]((48..57)+(65..90)+(97..122) | Get-Random)})
            "JSON_RESPONSE<<$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
            (Invoke-WebRequest -Uri "https://example.com").Content | Out-File -FilePath $env:GITHUB_ENV -Append
            "$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Print one
        run:
            Write-Host ${{ env.JSON_RESPONSE }}
      - name: Set the value in bash
        id: step_two
        shell: bash
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://example.com
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Print two
        run:
            Write-Host ${{ env.JSON_RESPONSE }}
    - name: Create Pull Request Comment
        id: create_comment
        run: |
          "COMMENT<<$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
          "## Comment"  | Out-File -FilePath $env:GITHUB_ENV -Append
          Title: This is a title  | Out-File -FilePath $env:GITHUB_ENV -Append
          Body: This is a body | Out-File -FilePath $env:GITHUB_ENV -Append
          "$EOF" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Print Comment
        run:
            Write-Host ${{ env.COMMENT }}
              